// <auto-generated />
namespace PRC.PacketBatchFiller.DataAccess
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nineteen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nineteen));
        
        string IMigrationMetadata.Id
        {
            get { return "201603090625398_Nineteen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
