// <auto-generated />
namespace PRC.PacketBatchFiller.DataAccess
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ten : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ten));
        
        string IMigrationMetadata.Id
        {
            get { return "201602171229215_Ten"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
